// Copyright Epic Games, Inc. All Rights Reserved.

#pragma once

#include "CoreMinimal.h"
#include "Blueprint/UserWidget.h"
#include "Types/SlateEnums.h"
#include "HronoMainMenuWidget.generated.h"

class UButton;
class UCheckBox;
class UComboBoxString;
class UFont;
class UInputMappingContext;
class USlider;
class USoundBase;
class USoundClass;
class USoundMix;
class UVerticalBox;
class UWidgetSwitcher;
class UWorld;

DECLARE_DYNAMIC_MULTICAST_DELEGATE(FHronoSessionMenuRequest);

/**
 * Native main menu with video/audio options and a read-only controls list.
 * Create a Widget Blueprint child to implement the session events. The default
 * layout is generated by C++, so a Designer hierarchy is optional.
 */
UCLASS(Blueprintable, BlueprintType)
class HRONO_API UHronoMainMenuWidget : public UUserWidget
{
	GENERATED_BODY()

public:
	UHronoMainMenuWidget(const FObjectInitializer& ObjectInitializer);

	/** Fired in addition to BP_CreateSessionRequested. */
	UPROPERTY(BlueprintAssignable, Category = "Main Menu|Sessions")
	FHronoSessionMenuRequest OnCreateSessionRequested;

	/** Fired in addition to BP_JoinSessionRequested. */
	UPROPERTY(BlueprintAssignable, Category = "Main Menu|Sessions")
	FHronoSessionMenuRequest OnJoinSessionRequested;

	/** Optional Sound Mix. A transient mix is created when this is empty. */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Main Menu|Audio")
	TObjectPtr<USoundMix> MenuSoundMix;

	/** Composite font used by the native menu layout. Defaults to HorrorEngine_Font. */
	UPROPERTY(EditDefaultsOnly, BlueprintReadOnly, Category = "Main Menu|Style")
	TObjectPtr<UFont> MenuFont;

	/** Gameplay destination used to identify and warm up the world after session travel. */
	UPROPERTY(EditDefaultsOnly, BlueprintReadOnly, Category = "Main Menu|Loading")
	TSoftObjectPtr<UWorld> GameplayMapToPreload;

	/** Assets spawned later that are not hard-referenced by GameplayMapToPreload. */
	UPROPERTY(EditDefaultsOnly, BlueprintReadOnly, Category = "Main Menu|Loading")
	TArray<TSoftObjectPtr<UObject>> AdditionalGameplayAssetsToPreload;

	/** When enabled, session Blueprint events fire only after configured content is resident. */
	UPROPERTY(EditDefaultsOnly, BlueprintReadOnly, Category = "Main Menu|Loading")
	bool bPreloadBeforeSessionRequest = true;

	/** Sound played when any menu button is pressed. Assign it in Widget Blueprint defaults. */
	UPROPERTY(EditDefaultsOnly, BlueprintReadOnly, Category = "Main Menu|Audio|Buttons")
	TObjectPtr<USoundBase> ButtonPressSound;

	UPROPERTY(EditDefaultsOnly, BlueprintReadOnly, Category = "Main Menu|Audio|Buttons", meta = (ClampMin = "0.0", UIMin = "0.0", UIMax = "2.0"))
	float ButtonPressSoundVolume = 1.0f;

	UPROPERTY(EditDefaultsOnly, BlueprintReadOnly, Category = "Main Menu|Style|Animation", meta = (ClampMin = "1.0", UIMin = "1.0", UIMax = "1.25"))
	float ButtonHoverScale = 1.07f;

	UPROPERTY(EditDefaultsOnly, BlueprintReadOnly, Category = "Main Menu|Style|Animation", meta = (ClampMin = "0.5", UIMin = "0.5", UIMax = "1.0"))
	float ButtonPressedScale = 0.94f;

	UPROPERTY(EditDefaultsOnly, BlueprintReadOnly, Category = "Main Menu|Style|Animation", meta = (ClampMin = "0.0", UIMin = "0.0", UIMax = "30.0"))
	float ButtonHoverOffset = 9.0f;

	UPROPERTY(EditDefaultsOnly, BlueprintReadOnly, Category = "Main Menu|Style|Animation", meta = (ClampMin = "1.0", UIMin = "1.0", UIMax = "30.0"))
	float ButtonAnimationSpeed = 14.0f;

	UPROPERTY(EditDefaultsOnly, BlueprintReadOnly, Category = "Main Menu|Style|Animation", meta = (ClampMin = "0.1", ClampMax = "1.0"))
	float ButtonIdleOpacity = 0.72f;

	UPROPERTY(EditDefaultsOnly, BlueprintReadOnly, Category = "Main Menu|Style|Animation")
	FLinearColor ButtonHoverColor = FLinearColor(0.72f, 0.07f, 0.04f, 1.0f);

	/** Optional override. The project default master Sound Class is used when empty. */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Main Menu|Audio")
	TObjectPtr<USoundClass> MasterSoundClass;

	/** Assign the Sound Class used by music assets for a separate music slider. */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Main Menu|Audio")
	TObjectPtr<USoundClass> MusicSoundClass;

	/** Assign the Sound Class used by effects assets for a separate effects slider. */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Main Menu|Audio")
	TObjectPtr<USoundClass> SfxSoundClass;

	/** Mapping contexts used to build the controls list. */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Main Menu|Controls")
	TArray<TSoftObjectPtr<UInputMappingContext>> ControlMappingContexts;

	/** Optional friendly labels keyed by Input Action asset name, for example IA_Interact. */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Main Menu|Controls")
	TMap<FName, FText> ControlDisplayNameOverrides;

	UFUNCTION(BlueprintCallable, Category = "Main Menu")
	void ShowMainMenu();

	UFUNCTION(BlueprintCallable, Category = "Main Menu")
	void ShowOptions();

	UFUNCTION(BlueprintCallable, Category = "Main Menu|Options")
	void ApplySettings();

	UFUNCTION(BlueprintCallable, Category = "Main Menu|Options")
	void CancelSettings();

	UFUNCTION(BlueprintCallable, Category = "Main Menu|Controls")
	void RefreshControlsList();

protected:
	virtual TSharedRef<SWidget> RebuildWidget() override;
	virtual void NativeConstruct() override;
	virtual void NativeDestruct() override;
	virtual void NativeTick(const FGeometry& MyGeometry, float InDeltaTime) override;

	/** Implement these two events in a Widget Blueprint child. */
	UFUNCTION(BlueprintImplementableEvent, Category = "Main Menu|Sessions", meta = (DisplayName = "Create Session Requested"))
	void BP_CreateSessionRequested();

	UFUNCTION(BlueprintImplementableEvent, Category = "Main Menu|Sessions", meta = (DisplayName = "Join Session Requested"))
	void BP_JoinSessionRequested();

private:
	void BuildDefaultWidgetTree();
	void ResolveNamedWidgets();
	void BindWidgetEvents();
	void RegisterAnimatedButton(UButton* Button);
	void PopulateGraphicsSettings();
	void LoadAudioSettings();
	void ApplyAudioSettings(float FadeTime);
	void SaveAudioSettings();
	FText GetFriendlyActionName(FName ActionName) const;
	void BeginSessionRequest(bool bCreateSession);
	void DispatchPendingSessionRequest();

	UFUNCTION()
	void HandleGameplayPreloadCompleted(bool bSuccess);

	UFUNCTION()
	void HandleCreateSessionClicked();

	UFUNCTION()
	void HandleJoinSessionClicked();

	UFUNCTION()
	void HandleOptionsClicked();

	UFUNCTION()
	void HandleExitClicked();

	UFUNCTION()
	void HandleApplyClicked();

	UFUNCTION()
	void HandleBackClicked();

	UFUNCTION()
	void HandleButtonPressed();

	UFUNCTION()
	void HandleMasterVolumeChanged(float Value);

	UFUNCTION()
	void HandleMusicVolumeChanged(float Value);

	UFUNCTION()
	void HandleSfxVolumeChanged(float Value);

	UPROPERTY(Transient)
	TObjectPtr<UWidgetSwitcher> PageSwitcher;

	UPROPERTY(Transient)
	TObjectPtr<UButton> CreateSessionButton;

	UPROPERTY(Transient)
	TObjectPtr<UButton> JoinSessionButton;

	UPROPERTY(Transient)
	TObjectPtr<UButton> OptionsButton;

	UPROPERTY(Transient)
	TObjectPtr<UButton> ExitButton;

	UPROPERTY(Transient)
	TObjectPtr<UButton> ApplyButton;

	UPROPERTY(Transient)
	TObjectPtr<UButton> BackButton;

	UPROPERTY(Transient)
	TObjectPtr<UComboBoxString> ResolutionCombo;

	UPROPERTY(Transient)
	TObjectPtr<UComboBoxString> WindowModeCombo;

	UPROPERTY(Transient)
	TObjectPtr<UComboBoxString> QualityCombo;

	UPROPERTY(Transient)
	TObjectPtr<UComboBoxString> FrameRateCombo;

	UPROPERTY(Transient)
	TObjectPtr<UCheckBox> VSyncCheckBox;

	UPROPERTY(Transient)
	TObjectPtr<USlider> MasterVolumeSlider;

	UPROPERTY(Transient)
	TObjectPtr<USlider> MusicVolumeSlider;

	UPROPERTY(Transient)
	TObjectPtr<USlider> SfxVolumeSlider;

	UPROPERTY(Transient)
	TObjectPtr<UVerticalBox> ControlsList;

	UPROPERTY(Transient)
	TObjectPtr<USoundMix> RuntimeSoundMix;

	float MasterVolume = 1.0f;
	float MusicVolume = 1.0f;
	float SfxVolume = 1.0f;
	float OriginalMasterVolume = 1.0f;
	float OriginalMusicVolume = 1.0f;
	float OriginalSfxVolume = 1.0f;
	bool bSoundMixPushed = false;
	bool bEventsBound = false;
	bool bPendingCreateSession = false;
	bool bSessionRequestPending = false;
	TArray<TWeakObjectPtr<UButton>> AnimatedButtons;
	TArray<float> ButtonHoverAlphas;
	TArray<float> ButtonScaleValues;

	static const FString AudioSettingsSlot;
};
