;METADATA=(Diff=true, UseCommands=true)

[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
+GameplayTagTableList=/Game/_Alex/Tags/GameplayTags.GameplayTags
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="DemonState",DevComment="")
+GameplayTagList=(Tag="DemonState.Attack",DevComment="")
+GameplayTagList=(Tag="DemonState.Routine",DevComment="")
+GameplayTagList=(Tag="Item.Future",DevComment="")
+GameplayTagList=(Tag="Item.Past",DevComment="")

